CREATE DATABASE TripService
USE TripService


CREATE TABLE Cities (
  Id INT PRIMARY KEY IDENTITY,
  Name VARCHAR(20) NOT NULL UNIQUE,
  CountryCode VARCHAR(2) NOT NULL
);

CREATE TABLE Hotels (
  Id INT PRIMARY KEY IDENTITY,
  Name VARCHAR(20) NOT NULL UNIQUE,
  CityId INT NOT NULL FOREIGN KEY REFERENCES Cities(Id),
  EmployeeCount INT NOT NULL,
  BaseRate DECIMAL(18,2)
);

CREATE TABLE Rooms (
  Id INT PRIMARY KEY IDENTITY,
  Price DECIMAL(18,2) NOT NULL,
  Type VARCHAR(20) NOT NULL,
  Beds INT NOT NULL,
  HotelId INT NOT NULL FOREIGN KEY REFERENCES Hotels(Id),
);

CREATE TABLE Trips (
  Id INT PRIMARY KEY IDENTITY,
  RoomId INT NOT NULL FOREIGN KEY REFERENCES Rooms(Id),
  BookDate DATETIME NOT NULL,
  ArrivalDate DATETIME NOT NULL,
  ReturnDate DATETIME NOT NULL,
  CancelDate DATETIME,
  CHECK(BookDate < ArrivalDate),
  CHECK(ArrivalDate < ReturnDate)
);

CREATE TABLE Accounts (
  Id INT PRIMARY KEY IDENTITY,
  FirstName VARCHAR(50) NOT NULL,
  MiddleName VARCHAR(20),
  LastName VARCHAR(50) NOT NULL,
  CityId INT NOT NULL FOREIGN KEY REFERENCES Cities(Id),
  BirthDate DATETIME NOT NULL,
  Email VARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE AccountsTrips (
  AccountId INT PRIMARY KEY IDENTITY,
  TripId INT NOT NULL FOREIGN KEY REFERENCES Trips(Id),
  Luggage INT NOT NULL CHECK(Luggage >= 0)
);
